export const defaultReport = {
  id: null,
  reportType: 'final',
  labReportRef: '',
  clientRequestRef: '',
  dateReported: '',
  dateReceived: '',
  clientName: '',
  project: '',
  projectClient: '',
  contractor: 'Not Given',
  consultant: 'Not Given',
  concreteSupplier: 'Not Given',
  mixGrade: 'C30 SRC',
  slump: '120',
  airContent: 'Not Given',
  samplingMethod: 'Not Given',
  otherInformation: 'Not Given',
  pourLocation: '',
  totalNoCubes: '1',
  dateOfCasting: '',
  sampledBy: 'Client',
  samplingLocation: '',
  samplingCertRef: 'Not Given',
  compactionMethod: 'Manual',
  laboratoryCuringMethod: 'BS EN 12390-2:2019',
  testMethod: 'BS EN 12390-3:2019',
  densityMethod: 'BS EN 12390-7:2019',
  volumeDetermination: 'By Calculation',
  testLocation: 'Wimpey Lab, Muscat',
  methodVariation: 'None',
  cubesDeliveredBy: 'Client',
  dimensions: 'Checked Nominal',
  nominalSize: '150X150X150',
  removalOfFins: 'Manual-Using steel file',
  curingAtLab: 'Water 20±2°C',
  testedBy: 'WL-1022',
  testResults: [
    {
      id: 1,
      clientRef: '',
      wLabSampleRef: '',
      reqTestAge: '28',
      actTestAge: '28',
      dateOfTest: '',
      conditionUponReceipt: 'Normal',
      conditionAtTest: 'Saturated',
      dimL: '150',
      dimW: '150',
      dimH: '150',
      mass: '',
      density: '',
      maxLoad: '',
      compStrength: '',
      typeOfFracture: 'SF',
    },
  ],
  notes: '* Measured dimensions of cube were within 1% of nominal size.',
  remarks: 'None',
  signedBy: '',
  position: 'Lab Supervisor (Civil)',
  certRef: 'WLR-CV-001 Issue 1 Rev. 02',
}
